/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_kwseeker_jni_prompt_Prompt */

#ifndef _Included_top_kwseeker_jni_prompt_Prompt
#define _Included_top_kwseeker_jni_prompt_Prompt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_kwseeker_jni_prompt_Prompt
 * Method:    getLine
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_top_kwseeker_jni_prompt_Prompt_getLine
  (JNIEnv *, jobject, jstring);

/*
 * Class:     top_kwseeker_jni_prompt_Prompt
 * Method:    getLine2
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_top_kwseeker_jni_prompt_Prompt_getLine2
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
