/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_kwseeker_jni_exception_CatchThrow */

#ifndef _Included_top_kwseeker_jni_exception_CatchThrow
#define _Included_top_kwseeker_jni_exception_CatchThrow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_kwseeker_jni_exception_CatchThrow
 * Method:    doIt
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_top_kwseeker_jni_exception_CatchThrow_doIt
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
