/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_kwseeker_jni_field_FieldAccess */

#ifndef _Included_top_kwseeker_jni_field_FieldAccess
#define _Included_top_kwseeker_jni_field_FieldAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_kwseeker_jni_field_FieldAccess
 * Method:    accessInstanceField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_top_kwseeker_jni_field_FieldAccess_accessInstanceField
  (JNIEnv *, jobject);

/*
 * Class:     top_kwseeker_jni_field_FieldAccess
 * Method:    accessStaticField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_top_kwseeker_jni_field_FieldAccess_accessStaticField
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
