/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_kwseeker_jni_hello_HelloJNI */

#ifndef _Included_top_kwseeker_jni_hello_HelloJNI
#define _Included_top_kwseeker_jni_hello_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_kwseeker_jni_hello_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_top_kwseeker_jni_hello_HelloJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
