/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_kwseeker_jni_array_Array */

#ifndef _Included_top_kwseeker_jni_array_Array
#define _Included_top_kwseeker_jni_array_Array
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_kwseeker_jni_array_Array
 * Method:    sumArray
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_top_kwseeker_jni_array_Array_sumArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     top_kwseeker_jni_array_Array
 * Method:    initInt2DArray
 * Signature: (I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_top_kwseeker_jni_array_Array_initInt2DArray
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
