/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_kwseeker_jni_method_MethodCall */

#ifndef _Included_top_kwseeker_jni_method_MethodCall
#define _Included_top_kwseeker_jni_method_MethodCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_kwseeker_jni_method_MethodCall
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_top_kwseeker_jni_method_MethodCall_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     top_kwseeker_jni_method_MethodCall
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_top_kwseeker_jni_method_MethodCall_nativeMethod
  (JNIEnv *, jobject);

/*
 * Class:     top_kwseeker_jni_method_MethodCall
 * Method:    nativeStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_top_kwseeker_jni_method_MethodCall_nativeStaticMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
